### ISSUE TITLE
Making video to play in loop

### ISSUE THREAD

**Issue by brijhub** [eneim/toro#333] opened 2018-05-16 07:55 UTC
I'm using below versions
 implementation "im.ene.toro3:toro:3.4.2"
 implementation "im.ene.toro3:toro-ext-exoplayer:3.4.2"

How can I play video in loop ?
I can't find any Lopping Helper class.

**Comment by yateeshkota** [comment] 2018-05-16 13:35
hi @brijhub  in your base app application class 
`public class YOUR_APP_NAME extends Application {
    
    public static Config config = null;
    private static ExoCreator exoCreator = null;
    private static long cacheFile = 2 * 1024 * 1024;

   

    @Override
    public void onCreate() {
        super.onCreate();
       

       
        String PATH = Environment.getExternalStorageDirectory() + "/" + "YOUR_APP_NAME" + "/";
        File folder = new File(PATH);
        if (!folder.exists()) {
            folder.mkdir();//If there is no folder it will be created.
        }
        SimpleCache cache = new SimpleCache(new File(PATH + "/toro_cache"), new LeastRecentlyUsedCacheEvictor(cacheFile));

        config = new Config.Builder().setMediaSourceBuilder(MediaSourceBuilder.LOOPING)
                .setCache(cache)
                .build();//this is use for lopping

        exoCreator = ToroExo.with(this).getCreator(config);
    }
}`

then in your video view holder 

` @Override
        public void initialize(@NonNull Container container, @Nullable PlaybackInfo playbackInfo) {
            if (helper == null) {
                helper = new ExoPlayerViewHelper(this, mediaUri, null, MyRole.config);//this will use to loop the video
//                helper =  new ExoPlayerViewHelper(this, mediaUri);//this not loop video
               
            }
            helper.initialize(container, playbackInfo);
        }`  

that can help you

**Comment by eneim** [comment] 2018-05-17 02:46
Thanks @yateeshkota . @brijhub Please refer to the comment above. Also I plan to simplify this in upcoming release, hope it can reduce your amount of code.

**Comment by brijhub** [comment] 2018-05-17 06:52
Yippee! Thanks @yateeshkota for your time and effort and of course @eneim for such superb library.
It worked for me so closing this issue.

**Comment by maxbaldrighi** [comment] 2018-06-11 19:21
Hello, I'm sorry for continuing the thread, but I would really appreciate some help...
I'm using:  
implementation "im.ene.toro3:toro:3.5.2"  
implementation "im.ene.toro3:toro-ext-exoplayer:3.5.2"
  
What I'm trying to achieve is looping my videos.
I've already tried all the different solutions proposed in various thread, like this one, or [here](https://github.com/eneim/toro/issues/244) where, following the sample code, I bound the `MediaSourceBuilder.LOOPING` directly to the PlayerHelper:  
```
public class LoopExoPlayerHelper extends ExoPlayerViewHelper {

	private static Config loopingConfig =
			new Config.Builder().setMediaSourceBuilder(MediaSourceBuilder.LOOPING).build();

	public LoopExoPlayerHelper(@NonNull ToroPlayer player, @NonNull Uri mediaUri) {
		// customized using Looping media source builder
		this(player, mediaUri, null);
	}

	private LoopExoPlayerHelper(@NonNull ToroPlayer player, @NonNull Uri mediaUri, String extension) {
		super(player, mediaUri, extension, loopingConfig);
	}

    }
```

But nothing has worked out well, the video just stops at its last frame, the STATE_IDLE is hit in the `EventListener` callback, and nothing else happens.
Regarding the `EventListener`, I aslo realized that the STATE_ENDED is never triggered because I tried to manually reset the player and start the playback again once that state was hit. But with no luck.

I think I have to add that my `Container` has the adapter as class implementing `CacheManager`.

Futhermore, reading at [the ExoPlayer docs](https://google.github.io/ExoPlayer/guide.html#seamlessly-looping-a-video), it says: 

> To loop indefinitely, it is usually better to use ExoPlayer.setRepeatMode instead of LoopingMediaSource

so I was wondering if there is a way to achieve video looping in this library with the repeat mode setting.
I tried the following but nothing happened: `mainView.getPlayer().setRepeatMode(Player.REPEAT_MODE_ONE);`, where `mainView` is my `PlayerView` object.

Can someone advise me? Thank you in advance.

**Comment by eneim** [comment] 2018-06-12 02:52
@brijhub Let me take a look.

**Comment by eneim** [comment] 2018-06-12 12:15
@brijhub Can you send me the Video Url that cause the error above?

Also, one design of Toro is to hide all direct interaction with PlayerView, so I will look into it to see if it can be done better. The LoopingMediaSource is used before setRepeatMode is implemented into ExoPlayer, so it will take some time. You can do it by yourself right now by implementing some classes by your own though. If you don't mind doing so while waiting for an update of this library, i can give some snippet.

**Comment by maxbaldrighi** [comment] 2018-06-12 13:49
Thank you very much!
Thanks also for the insight regarding .
But that was just curiosity
Some snippet would be much appreciated! My `setRepeatMode()` question was just out of curiosity. I would be perfectly fine using `LoopingMediaSource`, as long as it works! ;)

Here's the link of the video btw:
https://s3.amazonaws.com/hl-media-storage/02a6d890-d233-4ace-984b-0463ba588536.m4v

**Comment by eneim** [comment] 2018-06-12 14:11
@maxbaldrighi I have working demo with LoopingMediaSource, so it would work if the source doesn't cause any internal issue (it happens sometime FYI).

Below is a step by step show you how to customer the behavior your way.

[1] Customize your ``ExoCreator``: Extend ``DefaultExoCreator``, override ``createPlayer()`` and then, you can get the result of ``super.createPlayer()``, call ``setRepeatMode()`` on that instance, and return the instance there.

[2] Create new Helper using this constructor:

``public ExoPlayerViewHelper(@NonNull ToroPlayer player, @NonNull Uri uri, String fileExt,
      @NonNull ExoCreator creator)``

and pass an instance of the ExoCreator you build above. A suggestion is to have a singleton of that ExoCreator.

There, your SimpleExoPlayer instance should work your way. Not try it myself, but it is expected to work that way.

Your Video seems to failed even with ``setRepeatMode()`` set to ``Player.REPEAT_MODE_ONE``. Same error:

```
2018-06-12 23:10:39.614 9850-9888/im.ene.toro.sample E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:841)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.google.android.exoplayer2.upstream.DataSourceException
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:214)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:841) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
```

I will investigate this. But if your setup doesn't throw the Exception, please let me know.

**Comment by maxbaldrighi** [comment] 2018-06-12 14:17
Thank you!

Ah, ok, so you're saying that probably trying with another video the loop might work also with my current implementation, isn't it?

I'm gonna keep trying and keep you posted.

**Comment by eneim** [comment] 2018-06-12 14:19
@maxbaldrighi Yeah I guess the issue is caused by the Video. Trying to break it down now. But I suggest you to try with another one, better not m4v or mov (which is kind of close format).

**Comment by eneim** [comment] 2018-06-12 14:24
@maxbaldrighi FYI https://github.com/google/ExoPlayer/issues/3092

Maybe the Video file lacks of some header ... I will try to convert it to other container and double check a few times. But surely you should check your source too, if you control the source.

**Comment by maxbaldrighi** [comment] 2018-06-14 18:55
@eneim I'm sorry for getting back to you with such a delay.
I tested my current implementation with the LOOPING MediaSource directly put into the ExoPlayerHelper with a plain mp4 video and it works!

**Comment by eneim** [comment] 2018-06-14 23:48
@maxbaldrighi sounds good. I think current solution works at least for now. I will certainly update it with latest ExoPlayer spec and guideline. Please consider to close this. If you have further issue which may or may not related to looping playback, just create new issue.

**Closed** 2018-08-17 08:01 UTC

**Comment by manu10** [comment] 2018-09-14 14:59
Hi, In my case, the first solution provided by @yateeshkota didn't work, but when tried creating the simpleCache this way:
`SimpleCache cache = new SimpleCache(new File(getCacheDir(), "/toro_cache"),`
it worked fine.
