### ISSUE TITLE
toro player cache videos

### ISSUE THREAD

**Issue by kodlayanzi** [eneim/toro#290] opened 2018-01-21 17:31 UTC
can we cache videos? every play is redownload video source so my website's bandwidth was gone away.

**Comment by eneim** [comment] 2018-01-22 08:42
@kodlayanzi Have you read this article: https://medium.com/google-exoplayer/pre-caching-downloading-progressive-streams-in-exoplayer-3a816c75e8f6 

Hope this give you a solution. If it doesn't, please let me know.

**Comment by kodlayanzi** [comment] 2018-01-23 00:38
@eneim hi..

it is impossible to optimize that article to Toro.
Cache is the most important service in video player.

how can we fix this? This is important for my project.

**Comment by eneim** [comment] 2018-01-23 01:05
@kodlayanzi Got that, let me take a look on Cache mechanism and how to integrate it into my library.

**Comment by kodlayanzi** [comment] 2018-01-23 01:08
@eneim Iam waiting for your answer

**Comment by kodlayanzi** [comment] 2018-01-23 19:44
@eneim any suggestions?

**Comment by eneim** [comment] 2018-01-24 00:38
@kodlayanzi there is a few. I'm considering to bring CacheDataSourceFactory into the exoplayer extension. But to make it optional and abstract for many user, some more work need to be taken into account. At the mean time, you can manually copy-paste my helper class and replace the place using current DataSourceFactory with CacheDataSourceFactory. I will update this along with a better mechanism to reuse ExoPlayer instances :D.

**Comment by kodlayanzi** [comment] 2018-01-24 00:41
@eneim can you send me an example?

**Comment by eneim** [comment] 2018-01-24 00:46
@kodlayanzi this is where the MediaSource is created (as of 3.3.0): [source code of MediaSourceBuilder](https://github.com/eneim/toro/blob/release/v3.3.0/toro-exoplayer/src/main/java/im/ene/toro/exoplayer/MediaSourceBuilder.java).

[This line](https://github.com/eneim/toro/blob/release/v3.3.0/toro-exoplayer/src/main/java/im/ene/toro/exoplayer/MediaSourceBuilder.java#L101) is where the DataSourceFactory is built, which is a **DefaultDataSourceFactory**.

A cachable DataSourceFactory looks like below:

```java
mediaDataSourceFactory = new CacheDataSourceFactory(
        new SimpleCache(new File(context.getFilesDir() + "/toro_cache"), new LeastRecentlyUsedCacheEvictor(FILE_SIZE)),
        new DefaultDataSourceFactory(context, myAppName, bandwidthMeter));
```

The parameter is self-explained, you can try this approach. Read more on this here: [https://github.com/google/ExoPlayer/issues/2467](https://github.com/google/ExoPlayer/issues/2467) (a bit long though).

**Comment by kodlayanzi** [comment] 2018-01-24 00:48
@eneim tanx bro.. Iam waiting for Toro’s official update :)

**Comment by eneim** [comment] 2018-01-24 00:50
@kodlayanzi I will gather stuff up and see if it can be quick :).

**Comment by kodlayanzi** [comment] 2018-01-24 12:35
@eneim how fast it is, how good it is.

**Comment by eneim** [comment] 2018-01-28 09:01
I have some issues implementing this for Toro using ExoPlayer (already file issue in that repo). Once it has been fixed or cleared, I think this use case can be shipped.

**Comment by kodlayanzi** [comment] 2018-01-30 21:30
@eneim when can we see Toro 4.0?

**Comment by eneim** [comment] 2018-02-02 01:06
@kodlayanzi if it is about Cache, I'm fixing a bug on it, but it is quite 'rare' (~25% reproducible, at a certain condition) so I'm considering to push an alpha version for testing. But it is not 4.0 but 3.5.0. My draft for 4.0 is about completely different implementation :)

**Comment by abhinav272** [comment] 2018-02-02 05:28
@eneim is 3.5.0 on maven..?
Not able to access it.

**Comment by eneim** [comment] 2018-02-02 05:56
@abhinav272 not yet ... but can be done for testing soon so you can try it i weekend.

**Comment by jemshit** [comment] 2018-02-02 09:36
@eneim hi, a question,. If i use `PlayerSelector.NONE` video is not playing. But it seems from data usage toro downloads whole video! (not even buffering) every time i refresh page. Is this correct behaviour ? `PlayerSelector.NONE` is used to stop auto playing on 3G, but it does not stop downloading video. Any solution to stop downloading whole video until is starts to play. To test, [check this app ](https://play.google.com/store/apps/details?id=lol.playz.android)with video in feed, and check your data usage after each refresh.

**Comment by jemshit** [comment] 2018-02-02 11:42
@eneim or is there any way to limit buffer size (percent)?

**Comment by jemshit** [comment] 2018-02-02 11:57
I [found this](https://github.com/eneim/toro/blob/9308a85c380d7245af08c71990a7946152926973/toro-mopub/src/main/java/im/ene/toro/exoplayer/ExoPlayerHelper.java#L187), if i modify it with [CustomLoadController](https://github.com/Sriharia/ExoPlayer-StatsForNerds/blob/master/demo/src/main/java/com/google/android/exoplayer2/demo/CustomLoadControl.java) will it work?

**Comment by eneim** [comment] 2018-02-05 01:43
@jemshit Hi, sorry for late reply.

About the PlayerSelector.NONE issue, what format of Video you are loading? I follow ExoPlayer definition, not make any customization, so it may be something to do with ExoPlayer lib. But loading the data may depend on the format itself. I will try to see if just "preparing" the source make the download start, or something else.

About other stuff, yeah the Helper class is originally made to give user a concept of how things work, you can implement it independently from toro (so just not include toro-ext-exoplayer in your app, and create the helper by your own). Hope this help. I'm trying to make this more easily and flexible.

**Comment by FranciscoNin** [comment] 2018-02-05 13:50
Hi @eneim, this cache update is coming anytime soon? I'm trying to cache hls videos.
Thanks!

**Comment by jemshit** [comment] 2018-02-05 13:52
mp4 files (for PlayerSelector.NONE case)

**Comment by eneim** [comment] 2018-02-06 05:30
@FranciscoNin a alpha build will be released in one day or two, from there I'll get feedback as well as add improvement. If nothing goes wrong, this release will follow ExoPlayer 2.7.0 release (as there is one issue with broken cache file they are fixing).

**Comment by FranciscoNin** [comment] 2018-02-06 13:58
@eneim great! Thanks! Looking forward to test it.

**Comment by eneim** [comment] 2018-02-13 06:57
@jemshit @FranciscoNin it is a bit delayed, but you can now use Cache as well as new easy way to create SimpleExoPlayer. Also the Player instances are cache so that performance should be improved a little bit. Please let me know if you find it difficult to use, or anything else.

**Comment by kodlayanzi** [comment] 2018-02-21 16:45
@eneim how can i implement cache to my app? any demo app?

**Comment by eneim** [comment] 2018-02-22 02:27
@kodlayanzi In 3.4.0-alpha release, I put a new package for it here: [demo-exoplayer](https://github.com/eneim/toro/tree/dev-v3/demo-exoplayer). Hope it helps. Specifically, using a ExoCreator with cache is described here: [DemoApp.kt](https://github.com/eneim/toro/blob/dev-v3/demo-exoplayer/src/main/java/toro/demo/exoplayer/DemoApp.kt#L42). So the idea is: have your global Config, setup Cache and other options and then build an ExoCreator with that Config, pass it around for your App.

The terms ExoCreator, Config are new in 3.4.0, please take a look on the demo. If you have any question please let me know.

**Comment by prat-z** [comment] 2018-04-12 09:43
@eneim I am using version 3.4.0 of Toro, for playing HLS video, but caching is not working. I can see the cache files being created in the specified directory, but the video is being played from Upstream source only.
Thanks in advance.

**Comment by eneim** [comment] 2018-04-12 09:53
@prat-z can you reproduce this using ExoPlayer official demo app? I use its API so I guess something wrong is happening with it. I will double check the implementation of toro as well ...

**Comment by eneim** [comment] 2018-04-12 09:54
@prat-z Also, please update to at least 3.4.1 ... 3.4.0 is broken and I had to pull it down for that reason.

**Comment by prat-z** [comment] 2018-04-12 11:05
@eneim Tried with the demo app, it is the same behaviour, the problem must be with Exoplayer API. Thanks for your quick response!

**Comment by mwshubham** [comment] 2018-08-01 12:27
I got a folder created in my internal file dir. But there is no cache file. I guess there should be some cache video file whenever I play the file

**Comment by eneim** [comment] 2018-08-03 03:16
@mwshubham Can you show me the line you config Cache in your app?

**Comment by mwshubham** [comment] 2018-08-03 06:00
@eneim Thanks for your reply. Here is what I did https://hastebin.com/epekavubiz.sql

**Comment by eneim** [comment] 2018-08-08 02:31
@mwshubham I will take a look. Sorry so busy lately ...

**Comment by eneim** [comment] 2018-08-08 02:35
@mwshubham 

Here is your code in VideHolder:

```java
override fun initialize(container: Container, playbackInfo: PlaybackInfo) {
            if (exoPlayerViewHelper == null) {
                exoPlayerViewHelper = ExoPlayerViewHelper(this, mediaUri!!)
            }
            exoPlayerViewHelper?.initialize(container, playbackInfo)
}
```

You are not using your exoCreator here, so it will not use the Cache.

Try these:

```java
override fun initialize(container: Container, playbackInfo: PlaybackInfo) {
            if (exoPlayerViewHelper == null) {
                exoPlayerViewHelper = ExoPlayerViewHelper(this, mediaUri!!, null, AppController.exoCreator!!)
            }
            exoPlayerViewHelper?.initialize(container, playbackInfo)
}
```

**Comment by mwshubham** [comment] 2018-08-09 05:05
Thanks, @eneim I thought cache was enabled by default on configuration builder. Thanks for an easy library. It barely took any time to get the things ready.

**Comment by eneim** [comment] 2018-08-10 00:07
@mwshubham Will consider to make the configuration more obvious. Thanks for using toro :D.

**Closed by eneim** 2018-08-10 00:07 UTC

**Comment by li2** [comment] 2019-09-09 06:35
@eneim Thanks for such great lib.
I did a few hours research on this and was stuck on topic `exoplayer cache video` like CacheDataSourceFactory, finally, I found it's just simply one line to fix this issue mentioned in your comment.
It will be much more appreciated if you can put video cache solution in the README `Advance topics` then new guys come to this lib can easily resolve this issue.
Thanks again.

**Comment by eneim** [comment] 2019-09-10 05:05
@li2 Sounds fine to me, I will find time to improve the README.

**Comment by knowamit** [comment] 2020-03-12 16:45
I am using toro version 3.5.2 and below is code for pre-fetch video in Recyclerview but its seems video is not playing from cache. Please help 


``` DataSpec dataSpec = new DataSpec(Uri.parse(mediaUrl), 0, 100 * 20000, null);
            DataSource dataSource = new DefaultDataSource(NojotoApplication.getInstance(), new TransferListener<DataSource>() {
                @Override
                public void onTransferStart(com.google.android.exoplayer2.upstream.DataSource source, DataSpec dataSpec) {
                    Log.d(TAG, "onTransferStart: ");
                }

                @Override
                public void onBytesTransferred(com.google.android.exoplayer2.upstream.DataSource source, int bytesTransferred) {
                    Log.d(TAG, "onBytesTransferred: " + source.getUri().getPath());
                }

                @Override
                public void onTransferEnd(com.google.android.exoplayer2.upstream.DataSource source) {
                    Log.d(TAG, "onTransferEnd: " + attachmentUrl);
                }
            }, Util.getUserAgent(ApplicationContext(), "Nojoto"), false);

            CacheUtil.CachingCounters counters = new CacheUtil.CachingCounters();
                CacheUtil.cache(dataSpec, NojotoApplication.getInstance().cache, dataSource, counters);`

**Comment by shiv71** [comment] 2020-11-10 10:04
> I [found this](https://github.com/eneim/toro/blob/9308a85c380d7245af08c71990a7946152926973/toro-mopub/src/main/java/im/ene/toro/exoplayer/ExoPlayerHelper.java#L187), if i modify it with [CustomLoadController](https://github.com/Sriharia/ExoPlayer-StatsForNerds/blob/master/demo/src/main/java/com/google/android/exoplayer2/demo/CustomLoadControl.java) will it work?
> **Update**: it worked, changed `ExoPlayerHelper` to use CustomLoadControl (with custom buffer size), then changed `SimpleExoPlayerHelper` to use customized `ExoPlayerHelper`. Then used this `SimpleExoPlayerHelper` in recyclerview adapter

Can you share your configuration ? I am having an issue where in an HLS stream only highest quality bitrate stream is played. It's not switching to lower bitrate.
