### ISSUE TITLE
java.lang.NullPointerException in Container.Java

### ISSUE THREAD

**Issue by osamaaftab** [eneim/toro#315] opened 2018-03-20 19:03 UTC
> FATAL EXCEPTION: main
                                                                     Process: com.topthat.android, PID: 26890
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'int android.support.v7.widget.RecyclerView$LayoutManager.getChildCount()' on a null object reference
                                                                         at im.ene.toro.widget.Container.onScrollStateChanged(Container.java:241)
                                                                         at im.ene.toro.widget.Container$AnimatorHelper.handleMessage(Container.java:732)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

I  have been using 3.2.0 version for a while now when i am trying to update to the latest version my app is crashing for 3.4.1 version.

**Comment by eneim** [comment] 2018-03-20 21:26
Can you post your code you setup Container (LayoutManager, Adapter, etc).

**Comment by osamaaftab** [comment] 2018-04-04 16:27
public class ViewHolder extends RecyclerView.ViewHolder implements ToroPlayer {

        @Nullable
        ExoPlayerViewHelper helper;
        @Nullable
        private Uri mediaUri;
        @BindView(R.id.player)
        SimpleExoPlayerView playerView;
        @BindView(R.id.profile_img)
        ImageView profile_img;
        @BindView(R.id.name)
        TextView name;
        @BindView(R.id.date)
        TextView date;
        @BindView(R.id.desc)
        TextView desc;
        @BindView(R.id.status)
        Button status;
        

        public ViewHolder(View view) {
            super(view);
            ButterKnife.bind(this, view);
        }

        // called from Adapter to setup the media
        void bind(@NonNull RecyclerView.Adapter adapter, Uri item, List<Object> payloads) {
            if (item != null) {
                mediaUri = item;
            }
        }

        @NonNull
        @Override
        public View getPlayerView() {
            return playerView;
        }


        @NonNull
        @Override
        public PlaybackInfo getCurrentPlaybackInfo() {
            return helper != null ? helper.getLatestPlaybackInfo() : new PlaybackInfo();
        }


        @Override
        public void initialize(@NonNull Container container, @Nullable PlaybackInfo playbackInfo) {
            if (helper == null) {
                helper = new ExoPlayerViewHelper(this, mediaUri);
            }
            helper.initialize(container, playbackInfo);
        }


        @Override
        public void play() {
            if (helper != null) helper.play();
        }

        @Override
        public void pause() {
            if (helper != null) helper.pause();
        }

        @Override
        public boolean isPlaying() {
            return helper != null && helper.isPlaying();
        }

        @Override
        public void release() {
            if (helper != null) {
                helper.release();
                helper = null;
            }
        }

        @Override
        public boolean wantsToPlay() {
            return false;
        }

        @Override
        public int getPlayerOrder() {
            return getAdapterPosition();
        }

        @Override
        public void onSettled(Container container) {

        }
    }

I am using multiple ViewsHolders base on Items  in Container.

**Comment by osamaaftab** [comment] 2018-04-04 16:45
It's working the issue was here 
    `SimpleExoPlayerView playerView;`

**Comment by IgorKBigApps** [comment] 2018-06-12 12:42
I get the same issue from time to time do you have any idea how to fix it?

**Comment by eneim** [comment] 2018-06-12 12:54
@IgorKBigApps How do you setup your Container? The issue is caused by null LayoutManager. Also, there was a fix for this in 3.5.2 so I suggest you to try it.

**Comment by IgorKBigApps** [comment] 2018-06-12 13:18
thanks the problem seems to be fixed :)

**Closed** 2018-06-12 13:35 UTC
